import axios from 'axios'
import React, { useEffect } from 'react'
import { axiosNoAUth } from '../../API\'s/axios'

function PlatformGallery() {

    useEffect(() => [
        fetchGalleryImages()
    ],[])

    const fetchGalleryImages = async() => {
        try{
            const response = await axiosNoAUth.get('/explore?page=1&sort=top&time=all')
            console.log(response.data)
        }catch(error){
            console.error("Error fetching gallery images", error)
        }
    }

  return (
    <div className='container our-platform-gallery py-5'>
        <div className='our-platform-gallery-container'>
            <h1 className='mb-2'>Created with Genimagin</h1>
            <p>Get inspired by the images generated by our text-to-image AI. </p>
        </div>
       <div className='platform-gallery'>

       </div>
    </div>
  )
}

export default PlatformGallery;