import React, { useEffect, useState } from 'react'
import { axiosNoAUth } from '../../API\'s/axios'

function PlatformGallery() {

    const [galleryImages, setGalleryImages] = useState([]);

    useEffect(() => {
        fetchGalleryImages()
    },[])

    const fetchGalleryImages = async() => {
        try{
            const response = await axiosNoAUth.get('/explore?page=1&sort=top&time=all')
            console.log(response.data)
            setGalleryImages(response.data.images); 
        }catch(error){
            console.error("Error fetching gallery images", error)
        }
    }

  return (
    <div className='container our-platform-gallery py-5'>
        <div className='our-platform-gallery-container mb-5'>
            <h1 className='mb-2 h-2'>Created with Genimagin</h1>
            <p className='p-primary'>Get inspired by the images generated by our text-to-image AI. </p>
        </div>
       <div className='platform-gallery-image '>
            {galleryImages.length > 0 ? (
                    galleryImages.map((image, index) => (
                        <div key={index} className='col-6 col-md-4 col-lg-3 platform-image'>
                            <img 
                                src={image.image_url} 
                                alt={`Generated ${index}`} 
                                className='img-fluid rounded shadow'
                            />
                        </div>
                    ))
                ) : (
                    <p className='text-center w-100'>No images available</p>
            )}
       </div>
    </div>
  )
}

export default PlatformGallery;