import React, { useEffect, useRef, useState } from 'react'
import { axiosNoAUth } from '../../API\'s/axios'
import Masonry from "react-masonry-css";
import imagesLoaded from "imagesloaded";

function PlatformGallery() {


    const [galleryImages, setGalleryImages] = useState([]);
    // const gridRef = useRef(null);


    useEffect(() => {
        fetchGalleryImages()
    },[])


    const fetchGalleryImages = async() => {
        try{
            const response = await axiosNoAUth.get('/explore?page=1&sort=top&time=all')
            console.log(response.data)
            setGalleryImages(response.data.images); 
        }catch(error){
            console.error("Error fetching gallery images", error)
        }
    }

    useEffect(() => {
        if (galleryImages.length > 0) {
          const grid = document.querySelector(".platform-gallery-masonry");
          imagesLoaded(grid, () => {
            console.log("All images loaded, reflowing Masonry...");
          });
        }
      }, [galleryImages]);
    

  return (
    <div className='container our-platform-gallery py-5'>
        <div className='our-platform-gallery-container mb-5'>
            <h1 className='mb-2 h-2'>Created with Genimagin</h1>
            <p className='p-primary'>Get inspired by the images generated by our text-to-image AI. </p>
        </div>
       <div className='platform-gallery-image '>
        <Masonry
            breakpointCols={{ default: 4, 992: 3, 768: 2, 576: 1 }} // Adjusts for responsive layouts
            className="platform-gallery-masonry"
            columnClassName="platform-gallery-column"
        >
                {galleryImages.length > 0 ? (
                        galleryImages.map((image, index) => (
                            <div key={index} className='col-6 col-md-4 col-lg-3 platform-image '>
                                <img 
                                    src={image.image_url} 
                                    alt={`Generated ${index}`} 
                                    className='img-fluid shadow'
                                />
                            </div>
                        ))
                    ) : (
                        <p className='text-center w-100'>No images available</p>
                )}
            </Masonry>
       </div>
    </div>
  )
}

export default PlatformGallery;